module.exports = {
  someSidebar: {
    介绍: ['introduction', 'design-principles', 'benefits', 'comparison', 'principle'],
    起步: [
      // 'installation',
      'use-with-react',
      // 'use-with-vue',
      // 'use-with-rn',
      'use-with-taro',
      'use-with-vanilla',
    ],
    指南: [
      'basic',
      'pseudo',
      'responsive',
      'dynamic-style',
      'programmable',
      'unit',
      'config',
      // 'reuse',
      'theme',
      'plugin',
      // 'color-palette',
      'typescript',
      'attr-design-rule',
      'attr-table',
      'third',
    ],
    设计系统: [
      'design-system',
      'design-system-color',
      'design-system-typography',
      'design-system-spacing',
    ],
    属性: [
      'styli-ignore',
      'width',
      'height',
      'shape',
      'rounded',
      'typography',
      'background',
      'border',
      'outline',
      'padding',
      'margin',
      'display',
      'zIndex',
      'overflow',
      'position',
      'opacity',
      'shadow',
      'layout-engine',
      'flexbox',
      'cursor',
      'ellipsis',
      'space',
      'debug',
      'reset',
      'css-prop',
    ],
    Api: ['styled', 'createStyle'],
    组件: ['view', 'text', 'image', 'anchor'],
    示例: ['example-avatar', 'example-media-object'],
    问答: ['faq-1', 'faq-2', 'faq-3'],
  },
}
