module.exports = {
  someSidebar: {
    介绍: ['introduction', 'design-principles', 'benefits', 'comparison'],
    起步: [
      'installation',
      'use-with-react',
      'use-with-vue',
      'use-with-rn',
      'use-with-taro',
      'use-with-vanilla',
    ],
    指南: [
      'basic',
      'css-prop',
      'pseudo',
      'responsive',
      'dynamic-style',
      'programmable',
      'unit',
      'reuse',
      'theme',
      // 'plugin',
      // 'color-palette',
      'typescript',
    ],
    设计系统: [
      'design-system',
      'design-system-color',
      'design-system-typography',
      'design-system-spacing',
    ],
    原子属性: [
      'width',
      'height',
      'shape',
      'rounded',
      'typography',
      'background',
      'border',
      'shadow',
      'padding',
      'margin',
      // 'color',
      'opacity',
      'layout-engine',
      'flexbox',
    ],
    Api: ['styled', 'createStyle'],
    组件: ['view', 'text', 'image', 'anchor'],
    示例: ['example-avatar', 'example-media-object'],
    问答: ['faq-1', 'faq-2', 'faq-3'],
  },
}
