module.exports = {
  someSidebar: {
    Styli: ['introduction', 'installation', 'getting-started'],
    Guides: ['basic', 'adavanced', 'extend'],
    Philosophy: [
      'utility-first',
      'cross-framework',
      'type-safe',
      'less-code',
      'less-css',
      'programmable',
    ],
    Customization: ['customization-color'],
    Api: ['css'],
    Components: ['view', 'text', 'image', 'anchor'],
    Spacing: ['padding', 'margin'],
    Size: ['width', 'height', 'square', 'circle'],
    Layout: ['flex-layout'],
    Flexbox: ['flex'],
    Typography: ['font-size', 'font-color', 'font-weight', 'text-align', 'line-height', 'title'],
    Border: ['rounded', 'border-color'],
    Color: ['preset-color'],
    Background: [],
    Position: ['background-color'],
    Shadow: [],
  },
}
