module.exports = {
  someSidebar: {
    Styli: ['introduction', 'design-principles', 'benefits', 'comparison'],
    'Getting Started': [
      'installation',
      'use-with-react',
      'use-with-vue',
      'use-with-rn',
      // 'use-with-taro',
      'use-with-vanilla',
    ],
    'Design System': [
      'design-system',
      'design-system-color',
      'design-system-typography',
      'design-system-spacing',
    ],
    Guides: [
      'basic',
      'css-prop',
      'pseudo',
      'responsive',
      'dynamic-style',
      'programmable',
      // 'unit',
      'reuse',
      'theme',
      // 'plugin',
      'typescript',
    ],
    'Atomic Props': [
      'typography',
      'padding',
      'margin',
      'width',
      'height',
      'size',
      'circle',
      'color',
      'background-color',
      'layout-engine',
      'flexbox',
      'border',
      'rounded',
      'shadow',
      'opacity',
    ],
    Api: ['styled', 'css', 'createStyle'],
    // Components: ['view', 'text', 'image', 'anchor'],
    Examples: ['example-avatar', 'example-media-object'],
    FAQS: ['faq-1', 'faq-2', 'faq-3'],
  },
}
