module.exports = {
  someSidebar: {
    Styli: [
      'introduction',
      'installation',
      'getting-started',
      'guide',
      'configuration',
      'openness',
    ],
    Philosophy: [
      'utility-first',
      'framework-agnostic',
      'type-safe',
      'less-code',
      'less-css',
      'programmable',
    ],
    Props: [
      'padding',
      'margin',
      'width',
      'height',
      'square',
      'circle',
      'layout-engine',
      'flexbox',
      'typography',
      'title',
      'rounded',
      'border-color',
      'background-color',
      'shadow',
      'opacity',
      'preset-color',
    ],
    Api: ['styled', 'createStyle'],
    Components: ['view', 'text', 'image', 'anchor'],
    FAQS: ['opacity'],
  },
}
